[package]
name = "wasm_layout"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
wasm-bindgen = "0.2"


[features]
# 추후 geom/physics 모듈 분리용


[package.metadata.wasm-pack.profile.release]
wasm-opt = true